<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use PHPUnit\TextUI\XmlConfiguration\CodeCoverage\Report\Php;

class SurahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('table_surah')->insert([
            [
                'id' => 1,
                'nama_surah' => 'Al-Fatihah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Pembukaan',
                'jumlah_ayat' => 7,
                ],
                [
                'id' => 2,
                'nama_surah' => 'Al-Baqarah',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Sapi Betina',
                'jumlah_ayat' => 286,  
                ],
                [
                'id' => 3,
                'nama_surah' => 'Al-Imran',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Keluarga Imran',
                'jumlah_ayat' => 200,
                ],
                [
                'id' => 4,
                'nama_surah' => 'An-Nisa',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Wanita',
                'jumlah_ayat' => 176,
                ],
                [
                'id' => 5,
                'nama_surah' => 'Al-Maidah',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Hidangan Makanan',
                'jumlah_ayat' => 120,
                ],
                [
                'id' => 6,
                'nama_surah' => 'Al-Anam',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Binatang Ternak',
                'jumlah_ayat' => 165,
                ],
                [
                'id' => 7,
                'nama_surah' => 'Al-Araf',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Tempat Tertinggi',
                'jumlah_ayat' => 206,
                ],
                [
                'id' => 8,
                'nama_surah' => 'Al-Anfal',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Harta Rampasan Perang',
                'jumlah_ayat' => 75,
                ],
                [
                'id' => 9,
                'nama_surah' => 'At-Taubah',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Pengampunan',
                'jumlah_ayat' => 129,
                ],
                [
                'id' => 10,
                'nama_surah' => 'Yunus',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Nabi Yunus',
                'jumlah_ayat' => 109,
                ],
                [
                'id' => 11,
                'nama_surah' => 'Hud',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Nabi Hud',
                'jumlah_ayat' => 123,
                ],
                [
                'id' => 12,
                'nama_surah' => 'Yusuf',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Nabi Yusuf',
                'jumlah_ayat' => 111,
                ],
                [
                'id' => 13,
                'nama_surah' => 'Ar-Rad',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Guruh',
                'jumlah_ayat' => 43,
                ],
                [
                'id' => 14,
                'nama_surah' => 'Ibrahim',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Nabi Ibrahim',
                'jumlah_ayat' => 52,
                ],
                [
                'id' => 15,
                'nama_surah' => 'Al-Hijr',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Gunung Hijr',
                'jumlah_ayat' => 99,
                ],
                [
                'id' => 16,
                'nama_surah' => 'An-Nahl',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Lebah',
                'jumlah_ayat' => 128,
                ],
                [
                'id' => 17,
                'nama_surah' => 'Al-Isra',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Perjalanan di Waktu Malam',
                'jumlah_ayat' => 111,
                ],
                [
                'id' => 18,
                'nama_surah' => 'Al-Kahfi',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Penghuni-penghuni Gua',
                'jumlah_ayat' => 110,
                ],
                [
                'id' => 19,
                'nama_surah' => 'Maryam',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Maryam',
                'jumlah_ayat' => 98,
                ],
                [
                'id' => 20,
                'nama_surah' => 'Taha',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Taha',
                'jumlah_ayat' => 135,
                ],
                [
                'id' => 21,
                'nama_surah' => 'Al-Anbiya',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Nabi-nabi',
                'jumlah_ayat' => 112,
                ],
                [
                'id' => 22,
                'nama_surah' => 'Al-Hajj',
                'jenis_surah' => 'Madaniyah dan Makiyah',
                'arti_surah' => 'Haji',
                'jumlah_ayat' => 78,
                ],
                [
                'id' => 23,
                'nama_surah' => 'Al-Muminun',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Orang-orang Mukmin',
                'jumlah_ayat' => 118,
                ],
                [
                'id' => 24,
                'nama_surah' => 'An-Nur',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Cahaya',
                'jumlah_ayat' => 64,
                ],
                [
                'id' => 25,
                'nama_surah' => 'Al-Furqan',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Pembeda',
                'jumlah_ayat' => 77,
                ],
                [
                'id' => 26,
                'nama_surah' => 'Asy_Syuara',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Penyair',
                'jumlah_ayat' => 227,
                ],
                [
                'id' => 27,
                'nama_surah' => 'An_Naml',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Semut',
                'jumlah_ayat' => 93,
                ],
                [
                'id' => 28,
                'nama_surah' => 'Al-Qasas',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Cerita',
                'jumlah_ayat' => 88,
                ],
                [
                'id' => 29,
                'nama_surah' => 'Al-Ankabut',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Laba-laba',
                'jumlah_ayat' => 69,
                ],
                [
                'id' => 30,
                'nama_surah' => 'Ar-Rum',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Bangsa Romawi',
                'jumlah_ayat' => 60,
                ],
                [
                'id' => 31,
                'nama_surah' => 'Luqman',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Keluarga Luqman',
                'jumlah_ayat' => 34,
                ],
                [
                'id' => 32,
                'nama_surah' => 'As-Sajdah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Sajdah',
                'jumlah_ayat' => 30,
                ],
                [
                'id' => 33,
                'nama_surah' => 'Al-Ahzab',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Golongan-golongan yang Bersekutu',
                'jumlah_ayat' => 73,  
                ],
                [
                'id' => 34,
                'nama_surah' => 'Saba',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Kaum saba',
                'jumlah_ayat' => 54,
                ],
                [
                'id' => 35,
                'nama_surah' => 'Fatir',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Pencipta',
                'jumlah_ayat' => 45,
                ],
                [
                'id' => 36,
                'nama_surah' => 'Yasin',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Yasin',
                'jumlah_ayat' => 83,
                ],
                [
                'id' => 37,
                'nama_surah' => 'As-Saffat',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Barisan-barisan',
                'jumlah_ayat' => 182,
                ],
                [
                'id' => 38,
                'nama_surah' => 'Sad',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Shaad',
                'jumlah_ayat' => 88,
                ],
                [
                'id' => 39,
                'nama_surah' => 'Az-Zumar',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Rombongan-rombongan',
                'jumlah_ayat' => 75,
                ],
                [
                'id' => 40,
                'nama_surah' => 'Al-Muminun',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Orang yang beriman',
                'jumlah_ayat' => 85,
                ],
                [
                'id' => 41,
                'nama_surah' => 'Fussilat',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Yang dijelaskan',
                'jumlah_ayat' => 54,
                ],
                [
                'id' => 42,
                'nama_surah' => 'Asy-Syuara',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Musyawarah',
                'jumlah_ayat' => 53,
                ],
                [
                'id' => 43,
                'nama_surah' => 'Az-Zukhruf',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Perhiasan',
                'jumlah_ayat' => 89,
                ],
                [
                'id' => 44,
                'nama_surah' => 'Ad-Dukhan',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Kabut',
                'jumlah_ayat' => 59,
                ],
                [
                'id' => 45,
                'nama_surah' => 'Al-Jasiyah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Yang Bertekuk Lutut',
                'jumlah_ayat' => 37,
                ],
                [
                'id' => 46,
                'nama_surah' => 'Al-Ahqaf',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Bukit-bukit Pasir',
                'jumlah_ayat' => 35,  
                ],
                [
                'id' => 47,
                'nama_surah' => 'Muhammad',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Muhammad',
                'jumlah_ayat' => 38,
                ],
                [
                'id' => 48,
                'nama_surah' => 'Al-Fath',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Kemenangan',
                'jumlah_ayat' => 29,
                ],
                [
                'id' => 49,
                'nama_surah' => 'Al-Hujurat',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Kamar-kamar',
                'jumlah_ayat' => 18,
                ],
                [
                'id' => 50,
                'nama_surah' => 'Qaf',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Qaaf',
                'jumlah_ayat' => 45,
                ],
                [
                'id' => 51,
                'nama_surah' => 'Az-Zariyat',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Angin yang Menerbangkan',
                'jumlah_ayat' => 60,
                ],
                [
                'id' => 52,
                'nama_surah' => 'At-Tur',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Bukit',
                'jumlah_ayat' => 49,
                ],
                [
                'id' => 53,
                'nama_surah' => 'An-Najm',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Bintang',
                'jumlah_ayat' => 62,
                ],
                [
                'id' => 54,
                'nama_surah' => 'Al-Qamar',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Bulan',
                'jumlah_ayat' => 55,
                ],
                [
                'id' => 55,
                'nama_surah' => 'Ar-Rahman',
                'jenis_surah' => 'Madaniyah dan Makiyah',
                'arti_surah' => 'Yang Maha Pemurah',
                'jumlah_ayat' => 78,
                ],
                [
                'id' => 56,
                'nama_surah' => 'Al-Waqiah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Hari Kiamat',
                'jumlah_ayat' => 96,
                ],
                [
                'id' => 57,
                'nama_surah' => 'Al-Hadid',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Besi',
                'jumlah_ayat' => 29,
                ],
                [
                'id' => 58,
                'nama_surah' => 'Al-Mujadilah',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Wanita yang Mengajukan Gugatan',
                'jumlah_ayat' => 22,
                ],
                [
                'id' => 59,
                'nama_surah' => 'Al-Hasyr',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Pengusiran',
                'jumlah_ayat' => 24,  
                ],
                [
                'id' => 60,
                'nama_surah' => 'Al-Mumtahanah',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Wanita yang diuji',
                'jumlah_ayat' => 13,
                ],
                [
                'id' => 61,
                'nama_surah' => 'As-Saff',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Satu Barisan',
                'jumlah_ayat' => 14,
                ],
                [
                'id' => 62,
                'nama_surah' => 'Al-Jumuah',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Hari Jumat',
                'jumlah_ayat' => 11,
                ],
                [
                'id' => 63,
                'nama_surah' => 'Al-Munafiqun',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Orang-orang Munafik',
                'jumlah_ayat' => 11,
                ],
                [
                'id' => 64,
                'nama_surah' => 'At-Tagabun',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Hari di Nampakkan Kesalahan-kesalahan',
                'jumlah_ayat' => 18,
                ],
                [
                'id' => 65,
                'nama_surah' => 'At-Talaq',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Talak',
                'jumlah_ayat' => 12,
                ],
                [
                'id' => 66,
                'nama_surah' => 'At-Tahrim',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Mengharamkan',
                'jumlah_ayat' => 12,
                ],
                [
                'id' => 67,
                'nama_surah' => 'Al-Mulk',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Kerajaan',
                'jumlah_ayat' => 30,
                ],
                [
                'id' => 68,
                'nama_surah' => 'Al-Qalam',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Pena',
                'jumlah_ayat' => 52,
                ],
                [
                'id' => 69,
                'nama_surah' => 'Al-Haqqah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Hari Kiamat',
                'jumlah_ayat' => 52,
                ],
                [
                'id' => 70,
                'nama_surah' => 'Al-Maarij',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Tempat Naik',
                'jumlah_ayat' => 44,
                ],
                [
                'id' => 71,
                'nama_surah' => 'Nuh',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Nuh',
                'jumlah_ayat' => 28,
                ],
                [
                'id' => 72,
                'nama_surah' => 'Al-Jinn',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Jin',
                'jumlah_ayat' => 28,
                ],
                [
                'id' => 73,
                'nama_surah' => 'Al-Muzzammil',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Orang yang Berselimut',
                'jumlah_ayat' => 20,
                ],
                [
                'id' => 74,
                'nama_surah' => 'Al-Muddassir',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Orang yang Berkemul',
                'jumlah_ayat' => 56,
                ],
                [
                'id' => 75,
                'nama_surah' => 'Al-Qiyamah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Hari Kiamat',
                'jumlah_ayat' => 40,
                ],
                [
                'id' => 76,
                'nama_surah' => 'Al-Insan',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Manusia',
                'jumlah_ayat' => 31,
                ],
                [
                'id' => 77,
                'nama_surah' => 'Al-Mursalat',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Malaikat-malaikat yang Diutus',
                'jumlah_ayat' => 50,
                ],
                [
                'id' => 78,
                'nama_surah' => 'An-Naba',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Berita Besar',
                'jumlah_ayat' => 40,
                ],
                [
                'id' => 79,
                'nama_surah' => 'An-Naziat',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Malaikat-malaikat yang Mencabut',
                'jumlah_ayat' => 46,
                ],
                [
                'id' => 80,
                'nama_surah' => 'Abasa',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Ia Bermuka Masam',
                'jumlah_ayat' => 42,
                ],
                [
                'id' => 81,
                'nama_surah' => 'At-Takwir',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Menggulung',
                'jumlah_ayat' => 29,
                ],
                [
                'id' => 82,
                'nama_surah' => 'Al-Infitar',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Terbelah',
                'jumlah_ayat' => 19,
                ],
                [
                'id' => 83,
                'nama_surah' => 'Al-Mutaffifin',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Orang-orang yang Curang',
                'jumlah_ayat' => 36,
                ],
                [
                'id' => 84,
                'nama_surah' => 'Al-Insyiqaq',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Terbelah',
                'jumlah_ayat' => 25,
                ],
                [
                'id' => 85,
                'nama_surah' => 'Al-Buruj',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Gugusan Bintang-bintang',
                'jumlah_ayat' => 22,
                ],
                [
                'id' => 86,
                'nama_surah' => 'At-Tariq',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Yang Datang di Malam Hari',
                'jumlah_ayat' => 17,
                ],
                [
                'id' => 87,
                'nama_surah' => 'Al-Ala',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Yang Paling Tinggi',
                'jumlah_ayat' => 19,
                ],
                [
                'id' => 88,
                'nama_surah' => 'Al-Gasyiyah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Hari Pembalasan',
                'jumlah_ayat' => 26,
                ],
                [
                'id' => 89,
                'nama_surah' => 'Al-Fajr',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Fajar',
                'jumlah_ayat' => 30,
                ],
                [
                'id' => 90,
                'nama_surah' => 'Al-Balad',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Negeri',
                'jumlah_ayat' => 20,
                ],
                [
                'id' => 91,
                'nama_surah' => 'Asy-Syams',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Matahari',
                'jumlah_ayat' => 15,
                ],
                [
                'id' => 92,
                'nama_surah' => 'Al-Lail',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Malam',
                'jumlah_ayat' => 21,
                ],
                [
                'id' => 93,
                'nama_surah' => 'Ad-Dhuha',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Dhuha',
                'jumlah_ayat' => 11,
                ],
                [
                'id' => 94,
                'nama_surah' => 'Al-Insyirah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Melapangkan',
                'jumlah_ayat' => 8,
                ],
                [
                'id' => 95,
                'nama_surah' => 'At-Tin',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Buah Tin',
                'jumlah_ayat' => 8,
                ],
                [
                'id' => 96,
                'nama_surah' => 'Al-Alaq',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Segumpal Darah',
                'jumlah_ayat' => 19,
                ],
                [
                'id' => 97,
                'nama_surah' => 'Al-Qadar',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Kemuliaan',
                'jumlah_ayat' => 5,
                ],
                [
                'id' => 98,
                'nama_surah' => 'Al-Bayyinah',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Pembuktian',
                'jumlah_ayat' => 8,
                ],
                [
                'id' => 99,
                'nama_surah' => 'Al-Zazalah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Guncangan',
                'jumlah_ayat' => 8,
                ],
                [
                'id' => 100,
                'nama_surah' => 'Al-Adiyat',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Berlari Kencang',
                'jumlah_ayat' => 11,
                ],
                [
                'id' => 101,
                'nama_surah' => 'Al-Qariah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Hari Kiamat',
                'jumlah_ayat' => 11,
                ],
                [
                'id' => 102,
                'nama_surah' => 'At-Takasur',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Bermegah-megahan',
                'jumlah_ayat' => 8,
                ],
                [
                'id' => 103,
                'nama_surah' => 'Al-Asr',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Masa Waktu',
                'jumlah_ayat' => 3,
                ],
                [
                'id' => 104,
                'nama_surah' => 'Al-Humazah',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Pengumpat',
                'jumlah_ayat' => 9,
                ],
                [
                'id' => 105,
                'nama_surah' => 'Al-Fil',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Gajah',
                'jumlah_ayat' => 5,
                ],
                [
                'id' => 106,
                'nama_surah' => 'Quraisy',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Kaum Quraisy',
                'jumlah_ayat' => 4,
                ],
                [
                'id' => 107,
                'nama_surah' => 'Al-Maun',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Barang-barang Berguna',
                'jumlah_ayat' => 7,
                ],
                [
                'id' => 108,
                'nama_surah' => 'Al-Kausar',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Nikmat yang Berlimpah',
                'jumlah_ayat' => 3,
                ],
                [
                'id' => 109,
                'nama_surah' => 'Al-Kafirun',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Orang-orang Kafir',
                'jumlah_ayat' => 6,
                ],
                [
                'id' => 110,
                'nama_surah' => 'An-Nasr',
                'jenis_surah' => 'Madaniyah',
                'arti_surah' => 'Pertolongan',
                'jumlah_ayat' => 3,
                ],
                [
                'id' => 111,
                'nama_surah' => 'Al-Lahab',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Gejolak Api Sabut',
                'jumlah_ayat' => 5,
                ],
                [
                'id' => 112,
                'nama_surah' => 'Al-Ikhlas',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Ikhlas',
                'jumlah_ayat' => 4,
                ],
                [
                'id' => 113,
                'nama_surah' => 'Al-Falaq',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Waktu Shubuh',
                'jumlah_ayat' => 5,
                ],
                [
                'id' => 114,
                'nama_surah' => 'An-Nas',
                'jenis_surah' => 'Makiyah',
                'arti_surah' => 'Manusia',
                'jumlah_ayat' => 6,
                ],               
            ]);

    }
}

